const allKnives = [
    {
        "id": "2",
        "brand": "Arcos",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "24.0",
        "honing_add": "2.4",
        "category": "low_quality"
    },
    {
        "id": "3",
        "brand": "Baccarat",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "24.0",
        "honing_add": "2.4",
        "category": "low_quality"
    },
    {
        "id": "4",
        "brand": "Crofton",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "24.0",
        "honing_add": "2.0",
        "category": "low_quality"
    },
    {
        "id": "5",
        "brand": "Evolution",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "24.0",
        "honing_add": "2.0",
        "category": "low_quality"
    },
    {
        "id": "6",
        "brand": "FÜRI",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "24.0",
        "honing_add": "2.0",
        "category": "low_quality"
    },
    {
        "id": "7",
        "brand": "ICEL Benedita Portugal",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "28.0",
        "honing_add": "2.0",
        "category": "low_quality"
    },
    {
        "id": "8",
        "brand": "Jamie Oliver knives",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "24.0",
        "honing_add": "0.4",
        "category": "low_quality"
    },
    {
        "id": "9",
        "brand": "NELLA",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "24.0",
        "honing_add": "2.4",
        "category": "low_quality"
    },
    {
        "id": "10",
        "brand": "WiltShire",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "24.0",
        "honing_add": "2.0",
        "category": "low_quality"
    },
    {
        "id": "11",
        "brand": "F.Dick",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "30.0",
        "honing_add": "2.0",
        "category": "medium_quality"
    },
    {
        "id": "12",
        "brand": "IVO Portugal",
        "series": "",
        "steel": "X50CrMoV15",
        "carbon": "0.5",
        "CrMoV": "15.0",
        "angle": "24.0",
        "honing_add": "2.0",
        "category": "medium_quality"
    },
    {
        "id": "13",
        "brand": "Messermeister",
        "series": "",
        "steel": "X50CrMoV15",
        "carbon": "0.5",
        "CrMoV": "15.0",
        "angle": "24.0",
        "honing_add": "1.6",
        "category": "medium_quality"
    },
    {
        "id": "14",
        "brand": "MUNDIAL",
        "series": "",
        "steel": "x45CrMo14",
        "carbon": "0.45",
        "CrMoV": "14.0",
        "angle": "24.0",
        "honing_add": "2.0",
        "category": "medium_quality"
    },
    {
        "id": "15",
        "brand": "Opinel Carbone",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "24.0",
        "honing_add": "2.0",
        "category": "medium_quality"
    },
    {
        "id": "16",
        "brand": "Robert Welch",
        "series": "",
        "steel": "X50CrMoV15",
        "carbon": "0.5",
        "CrMoV": "15.0",
        "angle": "24.0",
        "honing_add": "1.6",
        "category": "medium_quality"
    },
    {
        "id": "17",
        "brand": "SCANPAN knives 1.4116",
        "series": "",
        "steel": "x45CrMoV15",
        "carbon": "0.45",
        "CrMoV": "15.0",
        "angle": "24.0",
        "honing_add": "2.0",
        "category": "medium_quality"
    },
    {
        "id": "18",
        "brand": "VG1",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "24.0",
        "honing_add": "0.4",
        "category": "medium_quality"
    },
    {
        "id": "19",
        "brand": "Victorinox",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "24.0",
        "honing_add": "2.0",
        "category": "medium_quality"
    },
    {
        "id": "20",
        "brand": "Victorinox SWIBO",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "24.0",
        "honing_add": "1.6",
        "category": "medium_quality"
    },
    {
        "id": "21",
        "brand": "Wüsthof",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "24.0",
        "honing_add": "2.0",
        "category": "medium_quality"
    },
    {
        "id": "22",
        "brand": "Zwilling Henckels",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "24.0",
        "honing_add": "2.0",
        "category": "medium_quality"
    },
    {
        "id": "23",
        "brand": "",
        "series": "",
        "steel": "440C",
        "carbon": "1.1",
        "CrMoV": "19.0",
        "angle": "20.0",
        "honing_add": "-0.1",
        "category": "high_quality"
    },
    {
        "id": "24",
        "brand": "BOKER",
        "series": "",
        "steel": "440C",
        "carbon": "1.1",
        "CrMoV": "19.0",
        "angle": "24.0",
        "honing_add": "0.4",
        "category": "high_quality"
    },
    {
        "id": "25",
        "brand": "",
        "series": "",
        "steel": "52100",
        "carbon": "0.96",
        "CrMoV": "3.0",
        "angle": "20.0",
        "honing_add": "0.8",
        "category": "high_quality"
    },
    {
        "id": "26",
        "brand": "",
        "series": "",
        "steel": "ATS-34",
        "carbon": "1.05",
        "CrMoV": "18.8",
        "angle": "24.0",
        "honing_add": "0.8",
        "category": "high_quality"
    },
    {
        "id": "27",
        "brand": "Damascus",
        "series": "",
        "steel": "15N20",
        "carbon": "0.75",
        "CrMoV": "3.5",
        "angle": "24.0",
        "honing_add": "1.2",
        "category": "high_quality"
    },
    {
        "id": "28",
        "brand": "GLOBAL Cromova-18",
        "series": "",
        "steel": "Cromova-18",
        "carbon": "0.55",
        "CrMoV": "17.0",
        "angle": "24.0",
        "honing_add": "1.2",
        "category": "high_quality"
    },
    {
        "id": "29",
        "brand": "Japanese high-carbon",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "20.0",
        "honing_add": "0.8",
        "category": "high_quality"
    },
    {
        "id": "30",
        "brand": "MIYABI",
        "series": "5000FCD",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "24.0",
        "honing_add": "1.6",
        "category": "high_quality"
    },
    {
        "id": "31",
        "brand": "MIYABI",
        "series": "FC61",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "24.0",
        "honing_add": "1.6",
        "category": "high_quality"
    },
    {
        "id": "32",
        "brand": "Tojiro",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "20.0",
        "honing_add": "-0.1",
        "category": "high_quality"
    },
    {
        "id": "33",
        "brand": "V-Toku2",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "20.0",
        "honing_add": "-0.1",
        "category": "high_quality"
    },
    {
        "id": "34",
        "brand": "Nitro-V",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "20.0",
        "honing_add": "1.6",
        "category": "high_quality"
    },
    {
        "id": "35",
        "brand": "RWL-34",
        "series": "",
        "steel": "",
        "carbon": "",
        "CrMoV": "",
        "angle": "24.0",
        "honing_add": "0.4",
        "category": "high_quality"
    },
    {
        "id": "36",
        "brand": "Sandvik",
        "series": "",
        "steel": "12C27",
        "carbon": "0.6",
        "CrMoV": "14.5",
        "angle": "24.0",
        "honing_add": "1.6",
        "category": "high_quality"
    },
    {
        "id": "37",
        "brand": "",
        "series": "",
        "steel": "VG10",
        "carbon": "1.0",
        "CrMoV": "18.0",
        "angle": "24.0",
        "honing_add": "0.8",
        "category": "high_quality"
    },
    {
        "id": "38",
        "brand": "",
        "series": "",
        "steel": "CPM 20CV",
        "carbon": "1.0",
        "CrMoV": "25.6",
        "angle": "24.0",
        "honing_add": "0.0",
        "category": "premium_quality"
    },
    {
        "id": "39",
        "brand": "",
        "series": "",
        "steel": "CPM S30V",
        "carbon": "1.45",
        "CrMoV": "20.0",
        "angle": "24.0",
        "honing_add": "-0.1",
        "category": "premium_quality"
    },
    {
        "id": "40",
        "brand": "",
        "series": "",
        "steel": "CPM S35VN",
        "carbon": "1.4",
        "CrMoV": "19.5",
        "angle": "24.0",
        "honing_add": "0.4",
        "category": "premium_quality"
    },
    {
        "id": "41",
        "brand": "",
        "series": "",
        "steel": "CPM S90V",
        "carbon": "2.3",
        "CrMoV": "24.0",
        "angle": "24.0",
        "honing_add": "0.0",
        "category": "premium_quality"
    },
    {
        "id": "42",
        "brand": "",
        "series": "",
        "steel": "D2",
        "carbon": "1.55",
        "CrMoV": "12.0",
        "angle": "30.0",
        "honing_add": "0.0",
        "category": "premium_quality"
    },
    {
        "id": "43",
        "brand": "",
        "series": "",
        "steel": "154CM",
        "carbon": "1.05",
        "CrMoV": "18.8",
        "angle": "24.0",
        "honing_add": "0.4",
        "category": "high_quality"
    }
];
